---
- name: Deploy Docker Container
  hosts: localhost
  
  tasks:
    - name: Install Docker.io
      apt:
        name: docker.io
        state: present

    - name: Pull Apache Docker image
      docker_image:
        name: httpd
        source: pull
        state: present

    - name: Create Docker network with desired subnet
      command: docker network create --driver=bridge --subnet=172.168.10.0/30 my_network
        
    - name: Run Apache Docker container with mounted volume
      docker_container:
        name: apache_container
        image: httpd
        state: started
        published_ports:
          - "8080:80"
        volumes:
          - "/Rizwana/index.html:/usr/local/apache2/htdocs"
        networks:
          - name: my_network
            ipv4_address: 172.168.10.2
    
     
