---
- name: Deploy Apache Docker Container
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Install Docker.io and Python Docker library
      apt:
        name: 
          - docker.io
          - python3-docker
        state: present

    - name: Pull Apache Docker image
      docker_image:
        name: httpd
        source: pull

    - name: Create directory for static web page
      file:
        path: /opt/static_web
        state: directory

    - name: Copy index.html file
      copy:
        src: index.html
        dest: /opt/static_web/index.html

    - name: Run Apache Docker container
      docker_container:
        name: apache_container
        image: httpd
        state: started
