---
- name: Deploy Apache Docker Container
  hosts: 10.0.0.4   
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Apache image
      docker_image:
        name: httpd:latest

    - name: Run Apache container
      docker_container:
        name: apache_container
        image: httpd:latest
        ports:
          - "80:80"
        detach: true
        networks:
          - name: apache_network
            driver: bridge
            ipam:
              config:
                - subnet: 172.168.10.0/30
        restart_policy: always
